### ISSUE TITLE
panic: "Write called after handler finished"

### ISSUE THREAD

**Issue by jm33-m0** [posener/h2conn#5]
`conn.Write()` causes a panic when the handler function has exited:

```
panic write called after handler finished
```

Can we add a check into

https://github.com/posener/h2conn/blob/13e7df33ed1548e5902d1b32bd6b5906cce194f5/server.go#L72

to make sure our `conn.Write()` returns an error  (instead of causing a panic) when the `conn` is not usable?

**Comment by posener** [comment]
Looking a bit deeper into the panic text, originally from [h2_bundle.go](https://github.com/golang/go/blob/22688f740dbbae281c1de09c2b4fe6520337a124/src/net/http/h2_bundle.go#L6244)

I'm guessing that you are running the code that writes and reads from the conn in a goroutine that writes to the connection after the `ServeHTTP` function returns. This is not allowed, and not required, since the `ServeHTTP` itself is running in a goroutine.

If you could provide a code example in which you get this error, I could help you fix it.

**Comment by jm33-m0** [comment]
Yes this can be prevented by checking the handler state, but I was thinking that sometimes we might actually do things like:
> running the code that writes and reads from the conn in a goroutine that writes to the connection after the ServeHTTP function returns
The reason is that we are using `Conn.Write()` in another goroutine, it can be inconvenient to check if the handler has finished. So I thought returning an `error` is better than causing a panic.

Maybe, it's better to add another property to `h2conn.Conn`? I think `Conn.IsOpen()` might be a good idea (probably more code).

The current code will work fine if we check the `Context` of the handler, but still, I think it's better to implement something that handles this in the library.

**Comment by posener** [comment]
Sorry, this sounds like a misuse of the `http2` library.
Having the `IsOpen` function will still not prevent race-conditions, since you are running in a different goroutine.

Writing a handler that uses the connection should be done carfully. If you are running goroutines, you should wait for all of them to finish before the handler returns, you can use `sync.WaitGroup` for that.

We can add documentation that clarifies this issue to the README if you want.

**Comment by jm33-m0** [comment]
What if we add a `Context` to `type Conn`?
https://github.com/posener/h2conn/blob/13e7df33ed1548e5902d1b32bd6b5906cce194f5/conn.go#L12-L29

**Comment by posener** [comment]
Sorry, but I don't understand what you are trying to fix.
Can you provide an example of a handler that causes this panic?

**Comment by jm33-m0** [comment]
> Sorry, but I don't understand what you are trying to fix.
No, I was trying to solve the `panic` at first, but as you explained there's nothing to fix, I think there's still a thing that might be helpful to users

**Comment by posener** [comment]
Usually when you see a panic in Go, it because you did something wrong. Try looking at the error and understand how you misused the code.
I'm closing this one, you are still open to contribute to the README to avoid confusion for others! :-)

Thanks!

**Comment by jm33-m0** [comment]
I totally understand.

> What if we add a Context to type Conn?

This seems irrelevant though, but it can be helpful for users to decide if the `Conn` is already done

```go
 func newConn(ctx context.Context, r io.Reader, wc io.WriteCloser) (*Conn, context.Context) { 
 	ctx, cancel := context.WithCancel(ctx) 
 	return &Conn{ 
 		r:      r, 
 		wc:     wc, 
 		cancel: cancel, 
                ctx: ctx, // add Context
 	}, ctx 
 } 
```
